name: Push to GCR GitHub Action

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

